Major usability upgrade (#96)
* types modifications

- update repo deps
- update node & npm to LTS version

* next

- update dependencies
- refactor ts logic according to new types and #86
- dump `type` from ConfiguStoreCredentialsConfiguration
- add `noUncheckedIndexedAccess` to main tsconfig
- add bunch of unit-tests

* update deps

* cd experiment 1

* cd experiment 2

* cd experiment 3

* cd experiment 4

* cd experiment 5

* cd experiment 6

* cd experiment 7

* cd experiment 8

* cd experiment 9

* cd experiment 10

* cd experiment 11

* cd experiment 12

* cd experiment 13

* cd experiment 14

* cd experiment 15

* cd experiment 16

* cd experiment 17

* cd experiment 18

* cd experiment 19

* cd experiment 20

* cd experiment 21

* cd experiment 22

* cd experiment 23

* cd experiment 24

* cd experiment 25

* cd experiment 26

* cd experiment 27

* cd experiment 28

* cd experiment 29

* next

- rm store.features
- update deps
- update node in CD
- rm * usage for delete command
- CONFIGU_SET template context

* Update EvalCommand.ts

* @configu/lib next

* @configu/cli next

* @configu/ts next - bugfixes

* fixes

* @configu/cli next

* chore: revert axios version bump

* chore: rebump axios version

* next

* skip empty tests

* remove empty tests

* update @configu deps

* update @configu deps

* Update package.json

* Update package.json

* ORM

* Update tsconfig.json

* Update tsconfig.json

---------

Co-authored-by: Richard <richard.akman1@gmail.com>

diff --git a/.github/actions/deploy-start-action/action.yml b/.github/actions/deploy-start-action/action.yml
--- a/.github/actions/deploy-start-action/action.yml
+++ b/.github/actions/deploy-start-action/action.yml
@@ -5,32 +5,70 @@ inputs:
     required: true
   slack-webhook:
     required: true
-  google-chat-webhook:
-    required: true
 
 outputs:
-  commit-sha:
-    description: "Commit SHA"
-    value: ${{ steps.commit-sha.outputs.sha_short }}
+  release-package:
+    description: "Release package"
+    value: ${{ steps.release-info.outputs.package }}
+  release-sha:
+    description: "Release sha"
+    value: ${{ steps.release-info.outputs.sha }}
+  release-branch:
+    description: "Release branch"
+    value: ${{ steps.release-info.outputs.branch }}
+  release-tag:
+    description: "Release tag"
+    value: ${{ steps.release-info.outputs.tag }}
   release-version:
     description: "Release version"
-    value: ${{ steps.release-tag.outputs.version }}
+    value: ${{ steps.release-info.outputs.version }}
+  release-channel:
+    description: "Release channel"
+    value: ${{ steps.release-info.outputs.channel }}
 
 runs:
   using: "composite"
   steps:
-    - name: Extract commit SHA version
-      id: commit-sha
+    - name: Extract release information
+      id: release-info
       shell: bash
       run: |
-        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+        sha=$(git rev-parse --short HEAD)
 
-    - name: Extract release tag version
-      id: release-tag
-      uses: olegtarasov/get-tag@v2.1.2
-      with:
-        tagRegex: "(?<package>.*)-v(?<version>.*)"
-        tagRegexGroup: 2
+        ref_tag=${{ github.event.ref }}
+        ref_branch=${{ github.event.base_ref }}
+
+        tag=${ref_tag#refs/tags/}
+        branch=${ref_branch#refs/heads/}
+
+        package=$(echo "$tag" | awk -F '-v' '{print $1}')
+        version=$(echo "$tag" | awk -F '-v' '{print $2}')
+
+        ref_channel=$(echo "$version" | awk -F '-' '{print $2}')
+        if [ "$branch" = "${{ github.event.repository.master_branch }}" ]; then
+          channel=latest
+        elif [ "next" = "${ref_channel%.*}" ]; then
+          channel=next
+        else
+          echo "couldn't resolve release channel based on the pushed tag"
+          echo "use <package>-v<X.Y.Z>          for "latest" channel"
+          echo "use <package>-v<X.Y.Z>-next.<I> for "next"   channel"
+          exit 1
+        fi
+
+        echo "package=$package" >> $GITHUB_OUTPUT
+        echo "sha=$sha" >> $GITHUB_OUTPUT
+        echo "branch=$branch" >> $GITHUB_OUTPUT
+        echo "tag=$tag" >> $GITHUB_OUTPUT
+        echo "version=$version" >> $GITHUB_OUTPUT
+        echo "channel=$channel" >> $GITHUB_OUTPUT
+
+        echo "package: $package"
+        echo "sha: $sha"
+        echo "branch: $branch"
+        echo "tag: $tag"
+        echo "version: $version"
+        echo "channel: $channel"
 
     - name: Post Slack build message
       id: slack
@@ -38,17 +76,11 @@ runs:
       with:
         payload: |
           {
-            "text": "${{ inputs.package-name }} v${{ steps.release-tag.outputs.version }} is now being deployed"
+            "text": "${{ inputs.package-name }} v${{ steps.release-info.outputs.version }} is now being deployed"
           }
       env:
         SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-
-    - name: Post Google Chat message
-      uses: julb/action-post-googlechat-message@v1
-      with:
-        message: "${{ inputs.package-name }} v${{ steps.release-tag.outputs.version }} is now being deployed"
-        gchat_webhook_url: ${{ inputs.google-chat-webhook }}
 
     - name: Create local bin dir
       shell: bash
