cd experiment 21

diff --git a/.github/actions/deploy-start-action/action.yml b/.github/actions/deploy-start-action/action.yml
--- a/.github/actions/deploy-start-action/action.yml
+++ b/.github/actions/deploy-start-action/action.yml
@@ -20,16 +20,6 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: Get branch names
-      id: branch-name
-      uses: tj-actions/branch-names@v6
-
-    - name: Print info
-      shell: bash
-      run: |
-        echo "Running on: ${{ steps.branch-name.outputs.tag }}"
-        echo "${{ toJSON(steps.branch-name.outputs) }}"
-
     # - name: Extract commit SHA version
     #   id: commit-sha
     #   shell: bash
@@ -43,37 +33,47 @@ runs:
     #     tagRegex: "(?<package>.*)-(?<version>.*)"
     #     tagRegexGroup: 2
 
-    # - name: Extract release channel
-    #   shell: bash
-    #   run: |
-    #     git --no-pager log -n 1 --pretty=%d HEAD
+    - name: Extract release channel
+      shell: bash
+      run: |
+        git --no-pager log -n 1 --pretty=%d HEAD
+        sha_short=$(git rev-parse --short HEAD)
 
-    #     ref=${{ github.ref }}
-    #     branch=$(git rev-parse --abbrev-ref HEAD)
-    #     tag=$(git describe --abbrev=0 --tags)
-    #     version=$(echo "$tag" | awk -F "${{ inputs.package-name }}-" '{print $2}')
-    #     if [ "$branch" = "main" ]; then
-    #       channel=stable
-    #     else
-    #       channel=next
-    #     fi
+        ref_tag=${{ github.event.ref }}
+        ref_branch=${{ github.event.base_ref }}
 
-    #     echo "ref: $ref"
-    #     echo "branch: $branch"
-    #     echo "tag: $tag"
-    #     echo "version: $version"
-    #     echo "channel: $channel"
+        tag=${ref_tag#refs/tags/}
+        branch=${ref_branch#refs/heads/}
+        version=$(echo "$tag" | awk -F "${{ inputs.package-name }}-" '{print $2}')
 
-    #     echo "inputs: ${{ toJSON(inputs) }}"
-    #     echo "env: ${{ env.GITHUB_REF_NAME }} ${{ env.GITHUB_REF_NAME }}"
-    #     echo "github: ${{ toJSON(github) }}"
+        if [ "$branch" = "${{ github.event.repository.master_branch }}" ]; then
+          channel=stable
+          # channel=latest
+        elif [ "next" = "${"$(echo "$tag" | awk -F "-" '{print $3}')"%.*}" ]; then
+          channel=next
+        else
+          echo "couldn't resolve release channel based on the pushed tag"
+          echo "use <package>-v<X.Y.Z>          for "stable" channel"
+          echo "use <package>-v<X.Y.Z>-next.<I> for "next"   channel"
+          exit 1
+        fi
 
-    #     # IFS='-' read -ra strarr <<< "$tag"
-    #     # echo "ref_tag: ${{ github.ref }}"
-    #     # echo "ref_branch: ${{ github.event.base_ref }}"
-    #     # echo "version: ${{ steps.release-tag.outputs.version }}"
-    #     # echo "${{ steps.ref.outputs.version }}"
-    #     # echo "${{ steps.ref.outputs.channel }}"
+        echo "ref: $ref"
+        echo "branch: $branch"
+        echo "tag: $tag"
+        echo "version: $version"
+        echo "channel: $channel"
+
+        # echo "inputs: ${{ toJSON(inputs) }}"
+        # echo "env: ${{ env.GITHUB_REF_NAME }} ${{ env.GITHUB_REF_NAME }}"
+        # echo "github: ${{ toJSON(github) }}"
+
+        # IFS='-' read -ra strarr <<< "$tag"
+        # echo "ref_tag: ${{ github.ref }}"
+        # echo "ref_branch: ${{ github.event.base_ref }}"
+        # echo "version: ${{ steps.release-tag.outputs.version }}"
+        # echo "${{ steps.ref.outputs.version }}"
+        # echo "${{ steps.ref.outputs.channel }}"
 
     # - name: Post Slack build message
     #   id: slack
