Cloud development environments

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -4,50 +4,51 @@ FROM ubuntu:latest
 # Maintainer
 LABEL maintainer="dev@configu.com"
 
-# Set environment variables to non-interactive (this ensures apt-get won't ask questions)
+# Set environment variables for non-interactive apt installs
 ENV DEBIAN_FRONTEND=non-interactive
+ENV HOME /root
+ENV PATH $HOME/.local/bin:$PATH
 
 # Arguments for versions
-ARG NODE_VERSION="18.15.0"
-ARG PYTHON_VERSION="3.9.16"
-ARG GO_VERSION="go1.21.3"
+ARG NODE_VERSION
+ARG PYTHON_VERSION
+ARG GO_VERSION
+
+# Validate ARGS
+RUN if [ -z "$NODE_VERSION" ]; then echo "NODE_VERSION argument is required" && exit 1; fi && \
+  if [ -z "$PYTHON_VERSION" ]; then echo "PYTHON_VERSION argument is required" && exit 1; fi && \
+  if [ -z "$GO_VERSION" ]; then echo "GO_VERSION argument is required" && exit 1; fi
 
 # Install basic dev tools
-RUN apt-get update && \
-  apt-get install -y git curl build-essential libssl-dev zlib1g-dev libbz2-dev \
-  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
-  xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git ca-certificates && \
-  apt-get clean
+RUN apt-get update && apt-get install -y \
+  git curl build-essential libssl-dev zlib1g-dev libbz2-dev \
+  libreadline-dev libsqlite3-dev wget llvm libncurses5-dev libncursesw5-dev \
+  xz-utils tk-dev libffi-dev liblzma-dev python3-openssl && \
+  rm -rf /var/lib/apt/lists/*
 
-# Install nvm with node and npm
+# Install nvm and then install Node.js and npm
 RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
-  . $HOME/.nvm/nvm.sh && \
-  nvm install $NODE_VERSION && \
-  nvm use $NODE_VERSION
+  . $HOME/.nvm/nvm.sh && nvm install $NODE_VERSION
 
-# Install pyenv
+# Install pyenv and Python
 RUN curl https://pyenv.run | bash
-
-# Adjust PATH for pyenv
-ENV HOME /root
 ENV PATH $HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH
+RUN pyenv install $PYTHON_VERSION && pyenv global $PYTHON_VERSION
 
-# Install Python with pyenv
-RUN pyenv install $PYTHON_VERSION && \
-  pyenv global $PYTHON_VERSION
-
-# Install poetry
+# Install poetry globally
 RUN curl -sSL https://install.python-poetry.org | python3 -
-RUN poetry env use $HOME/.pyenv/shims/python
 
-# Install gvm to manage Go versions
-RUN bash -c 'bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)'
-
-# Install Go using gvm
-RUN /bin/bash -c "source $HOME/.gvm/scripts/gvm && gvm install $GO_VERSION --default"
+# Install goenv and Go
+RUN git clone https://github.com/syndbg/goenv.git ~/.goenv && \
+  echo 'export GOENV_ROOT="$HOME/.goenv"' >> ~/.bashrc && \
+  echo 'export PATH="$GOENV_ROOT/bin:$PATH"' >> ~/.bashrc && \
+  echo 'eval "$(goenv init -)"' >> ~/.bashrc && \
+  . ~/.bashrc && \
+  goenv install $GO_VERSION && \
+  goenv global $GO_VERSION
 
 # Cleanup
 RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
-# Define the default command
+# Default command
 CMD ["/bin/bash"]
