richi cr

diff --git a/.github/workflows/cd-cli.yml b/.github/workflows/cd-cli.yml
--- a/.github/workflows/cd-cli.yml
+++ b/.github/workflows/cd-cli.yml
@@ -183,24 +183,57 @@ jobs:
           files: |
             ${{ steps.release.outputs.package_path }}/dist/*
 
-      - name: Delete previous tag and release
-        run: |
-          gh release delete ${{ steps.release.outputs.package }}/${{ steps.release.outputs.channel }} --cleanup-tag --yes || true
+      # - name: Delete previous tag and release
+      #     gh release delete ${{ steps.release.outputs.package }}/${{ steps.release.outputs.channel }} --cleanup-tag --yes || true
 
-      - name: Create updated tag and release
-        uses: softprops/action-gh-release@v2
-        if: ${{ startsWith(github.ref, 'refs/tags/') }}
-        with:
-          tag_name: ${{ steps.release.outputs.package }}/${{ steps.release.outputs.channel }}
-          make_latest: ${{ steps.release.outputs.channel == 'latest' }}
-          prerelease: ${{ steps.release.outputs.channel != 'latest' }}
-          files: |
-            # todo: handle latest and next releases
-            ${{ steps.release.outputs.package_path }}/dist/*
+      # - name: Create updated tag and release
+      #   uses: softprops/action-gh-release@v2
+      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      #   with:
+      #     tag_name: ${{ steps.release.outputs.package }}/${{ steps.release.outputs.channel }}
+      #     make_latest: ${{ steps.release.outputs.channel == 'latest' }}
+      #     prerelease: ${{ steps.release.outputs.channel != 'latest' }}
+      #     files: |
+      #       # todo: handle latest and next releases
+      #       ${{ steps.release.outputs.package_path }}/dist/*
+
+  release-npm:
+    runs-on: ubuntu-latest
+    needs: build-binary
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: ./.github/actions/get-release-action
+        id: release
+
+      - uses: ./.github/actions/ts-env-action
+        id: env
+
+      - name: Bump package version
+        shell: bash
+        run: |
+          pnpm --filter ${{ steps.release.outputs.package_name }} exec \
+            npm --no-git-tag-version version ${{ steps.release.outputs.version }}
+
+      - name: Build package code
+        run: |
+          pnpm run build
+          pnpm --filter ${{ steps.release.outputs.package_name }} run \
+            build
+
+      - name: Publish to npm
+        run: |
+          git diff
+          pnpm --filter ${{ steps.release.outputs.package_name }} publish \
+            --access public --provenance --no-git-checks --tag ${{ steps.release.outputs.channel }}
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
   check-release:
     runs-on: ${{ matrix.runner }}
-    needs: release-binary
+    needs:
+      - release-binary
+      - release-npm
     strategy:
       matrix:
         runner:
@@ -213,7 +246,7 @@ jobs:
       - uses: ./.github/actions/get-release-action
         id: release
 
-      - name: Check installable on ${{ matrix.runner }}
+      - name: Check binary on ${{ matrix.runner }}
         if: ${{ matrix.runner != 'windows-latest' }}
         shell: bash
         env:
@@ -223,7 +256,7 @@ jobs:
           curl -fsSL https://raw.githubusercontent.com/configu/configu/refs/heads/${{ steps.release.outputs.branch }}/${{ steps.release.outputs.package_path }}/install.sh | sh
           ./configu/bin/configu -v
 
-      - name: Check release on ${{ matrix.runner }}
+      - name: Check binary on ${{ matrix.runner }}
         if: ${{ matrix.runner == 'windows-latest' }}
         shell: pwsh
         env:
@@ -232,6 +265,15 @@ jobs:
         run: |
           irm https://raw.githubusercontent.com/configu/configu/refs/heads/${{ steps.release.outputs.branch }}/${{ steps.release.outputs.package_path }}/install.ps1 | iex
           ./configu/bin/configu -v
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version-file: '.node-version'
+
+      - name: Check npm on ${{ matrix.runner }}
+        run: |
+          npm i -g configu@${{ steps.release.outputs.version }}
+          configu -v
 
   post-release:
     runs-on: ubuntu-latest
